
name: CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Change directory to root
        run: cd ..

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies with poetry
        run: poetry install

      - name: Run black
        run: poetry run black --check .
        env:
          PIP_CACHE_DIR: .cache/pip

      - name: Run flake8
        run: poetry run flake8 .
        env:
          PIP_CACHE_DIR: .cache/pip

      - name: Run tests with pytest
        run: poetry run pytest
        env:
          PIP_CACHE_DIR: .cache/pip